import {ReactNode} from "react";
import './globals.scss'
import { Inter } from 'next/font/google'
import {Footer, Header} from "@/components";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen bg-gray-100 ${inter.className}`}>
      <Header/>
      <main className="p-3">{children}</main>
      <Footer/>
      </body>
    </html>
  )
}
